// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MulakatAPI.Repository;

#nullable disable

namespace MulakatAPI.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250811103655_mig2")]
    partial class mig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MulakatAPI.Core.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SanatciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SanatciId");

                    b.ToTable("Albumler", (string)null);
                });

            modelBuilder.Entity("MulakatAPI.Core.Models.CalmaListe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CalmaListeleri", (string)null);
                });

            modelBuilder.Entity("MulakatAPI.Core.Models.CalmaListeSarki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalmaListeId")
                        .HasColumnType("int");

                    b.Property<int>("SarkiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalmaListeId");

                    b.HasIndex("SarkiId", "CalmaListeId")
                        .IsUnique();

                    b.ToTable("CalmaListeSarkilar", (string)null);
                });

            modelBuilder.Entity("MulakatAPI.Core.Models.Sanatci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KurulusTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sanatcilar", (string)null);
                });

            modelBuilder.Entity("MulakatAPI.Core.Models.Sarki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("SanatciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Sarkilar", (string)null);
                });

            modelBuilder.Entity("MulakatAPI.Core.Models.Album", b =>
                {
                    b.HasOne("MulakatAPI.Core.Models.Sanatci", "Sanatci")
                        .WithMany("Albums")
                        .HasForeignKey("SanatciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sanatci");
                });

            modelBuilder.Entity("MulakatAPI.Core.Models.CalmaListeSarki", b =>
                {
                    b.HasOne("MulakatAPI.Core.Models.CalmaListe", "CalmaListe")
                        .WithMany("CalmaListeSarkis")
                        .HasForeignKey("CalmaListeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MulakatAPI.Core.Models.Sarki", "Sarki")
                        .WithMany("CalmaListeSarkis")
                        .HasForeignKey("SarkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalmaListe");

                    b.Navigation("Sarki");
                });

            modelBuilder.Entity("MulakatAPI.Core.Models.Sarki", b =>
                {
                    b.HasOne("MulakatAPI.Core.Models.Album", "Album")
                        .WithMany("Sarkis")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("MulakatAPI.Core.Models.Album", b =>
                {
                    b.Navigation("Sarkis");
                });

            modelBuilder.Entity("MulakatAPI.Core.Models.CalmaListe", b =>
                {
                    b.Navigation("CalmaListeSarkis");
                });

            modelBuilder.Entity("MulakatAPI.Core.Models.Sanatci", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("MulakatAPI.Core.Models.Sarki", b =>
                {
                    b.Navigation("CalmaListeSarkis");
                });
#pragma warning restore 612, 618
        }
    }
}
